

version: "3.8"
services:
  frontend:
    build: ./Frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8100:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=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
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
   # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

