
services:
  frontend:
    build: ./Frontend
    container_name: react_frontend
    ports:
      - "5173:5500"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8500"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

